jobs:
  test:
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -V --no-transfer-progress clean install
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        os:
        - ubuntu-latest
        - windows-latest
      max-parallel: 64
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
